### ISSUE TITLE
Test Failure Tracking 

### ISSUE THREAD

**Issue by mpickering** [tweag/ghc#35]
Currently the following tests fail.

# Known Failures

These are failures which are known to be failing on the master branch.

- [x] ghcpkg05

# ETA Problems 

Problems which we could solve be eta-expanding to cast the linear to an unrestricted arrow. 

- [x] cgrun075
- [x] cgrun076
- [x] T10414
- [x] T11108
- [x] T11459
- [x] T13454
- [x] T14171
- [x] T3731
- [x] T7264
- [x] T7919
- [x] T9892
- [x] ds055
- [x] qq005
- [x] qq006
- [x] tcfail206

Status: Ignored.

# Pretty Printing Changes

Failures caused by the pretty printer printing additional linearity information spuriously. 

- [x] T2431
- [x] Roles13
- [x] T13143
- [x] T2851
- [x] T3717
- [x] T3772
- [x] T4398
- [x] T4908
- [x] T4930
- [x] T5217
- [x] T7785
- [x] T8848a
- [x] T9071
- [x] T9305
- [x] drvfail-functor2
- [x] drvfail001
- [x] drvfail002
- [x] drvfail003
- [x] drvfail007
- [x] drvfail013
- [x] par01
- [x] spec-inline
- [x] tcfail046
- [x] tcfail118
- [x] tcfail169

Status: Fixed.

# Types of data constructor are now linear

Problems caused in the pretty-printing of the types of data constructors. They now have a linear
type so the output differs from before when printing them in error messages for example.

- [ ] ADT
- [ ] Roles1
- [ ] Roles2
- [ ] SkipMany
- [ ] T12550
- [ ] T3017
- [x] T7627
- [ ] ghci025
- [x] holes
- [x] holes3
- [ ] tc231
- [x] tcfail099
- [x] tcfail156
- [x] tcfail179
- [x] valid_substitutions
- [ ] T8958
- [x] T2414
- [x] T12083a
- [x] TypeAppData - A test which makes pattern synonyms in ghci and then things go horribly wrong

Status: Ignored

# GHC API Changes

Tests which use the GHC API which has changed due to additional arguments for linearity

- [x] CallArity1
- [x] DumpParsedAst
- [x] DumpRenamedAst
- [x] T14189

# Incorrect export error message 

These tests are missing the line below in their error message. It could be due to a mistake in merging

```
A data constructor of that name is in scope; did you mean DataKinds?
```

- [x] mod124
- [x] mod127
- [x] mod29
- [x] readFail001

# Monad Comprehension Desugaring

These tests all fail because of the way monad comprehensions are desugared. I think it's similar to the problems which we had with Data instances. 

- [x] T14591
- [x] T5522
- [x] mc01
- [x] mc03
- [x] mc06
- [x] mc08
- [x] mc10
- [x] mc11
- [x] mc12
- [x] mc14
- [x] mc15
- [x] mc16
- [x] mc17
- [x] mc18
- [x] mc20
- [x] mc21
- [x] mc22
- [x] mc24
- [x] mc25

Status: Fixed, caused by a missing fixity declaration

# Changes to Data desugaring (which will be reverted eventually)

We had to eta-expand the derived instances for Data which shows up in this tests.

- [x] T14682 #42 

# Linearity Failure

New Core Lint errors caused by my new linearity checking pass.

- [x] T1735  - Fails with core lint error - #40
- [ ] T7360 - Skipped due to data constructors having linear types but fails with linearity
- [x] T8331 - fails with core lint enabled but passes without

# Simplifier stats changed (probably due to eta expansion)

- [x] T3234 - #41

# CSE

It appears that CSE is not firing as it was before in these tests.

- [ ] T7116 - #37
- [ ] T5996 - #37
- [ ] T13340 - #37

Probably due to an incorrect implementation in: d156ef4459acd2feb20a68c07f96631785349d5e

# Coercible doesn't understand linearity (but should it?)
- [x] TcCoercible - #38

# Unknown 

Tests without a quick analysis

- [x] T13233 - A very mysterious `isUnliftedType` panic. This function is used all over the compiler, I couldn't get a foothold to start debugging this yet. #39
- [x] T10619 - spooky stderr
- [x] T12603 - spooky stderr
- [x] T13244 - Looks like the same as T13233 but less mysterious #39
- [x] T13642 - ss
- [x] T1595 - ss
- [x] T5366 - ss
- [x] T9662 - ss
- [ ] inline-check - #43 Seems like a function doesn't get inlined that does before. Need to investigate more.
- [x] print020 - #44 Out of scope errors -

**Comment by aspiwack** [comment]
These have been reclassified since. Let's close.
